import type { ExecutionStatus } from '@prisma/client'
import type { StructuredError } from './domain'
import { AppError } from './errors'
export type ExecutionLimits = { timeoutMs: number; maxOutputBytes: number; allowNetwork: boolean }
export const defaultExecutionLimits: ExecutionLimits = { timeoutMs: 10_000, maxOutputBytes: 64_000, allowNetwork: false }
export function validateExecutionLimits(limits: ExecutionLimits): ExecutionLimits { if (!Number.isInteger(limits.timeoutMs) || limits.timeoutMs < 100 || limits.timeoutMs > 120_000 || !Number.isInteger(limits.maxOutputBytes) || limits.maxOutputBytes < 1 || limits.maxOutputBytes > 1_000_000) throw new AppError({ code: 'INVALID_EXECUTION_LIMITS', message: 'Execution limits are outside the allowed range.', category: 'validation', retryable: false }); return limits }
export type ExecutionKind = 'file_read' | 'file_write' | 'list' | 'inspect' | 'test' | 'build' | 'git'
export type ExecutionRequest = { projectId: string; taskId?: string; agentRunId?: string; kind: ExecutionKind; input: Record<string, unknown>; limits: ExecutionLimits }
export type ExecutionResult = { status: ExecutionStatus; stdout: string; stderr: string; exitCode?: number; durationMs: number; error?: StructuredError; metadata: Record<string, unknown> }
export interface ControlledExecutor { execute(request: ExecutionRequest): Promise<ExecutionResult> }
export class RejectingExecutor implements ControlledExecutor { async execute(request: ExecutionRequest): Promise<ExecutionResult> { const limits = validateExecutionLimits(request.limits); const message = limits.allowNetwork ? 'Network access is disabled for the foundation executor.' : `Controlled executor for ${request.kind} is not configured.`; return { status: 'rejected', stdout: '', stderr: '', durationMs: 0, error: { code: limits.allowNetwork ? 'NETWORK_NOT_ALLOWED' : 'EXECUTOR_NOT_CONFIGURED', message, category: 'execution', retryable: false }, metadata: { projectId: request.projectId, taskId: request.taskId, agentRunId: request.agentRunId, limits } } } }
export const executionTransitions: Record<ExecutionStatus, readonly ExecutionStatus[]> = { queued: ['queued', 'running', 'rejected'], running: ['running', 'succeeded', 'failed', 'timed_out', 'rejected'], succeeded: ['succeeded'], failed: ['failed'], timed_out: ['timed_out'], rejected: ['rejected'] }
export function assertExecutionTransition(from: ExecutionStatus, to: ExecutionStatus) { if (!executionTransitions[from].includes(to)) throw new AppError({ code: 'INVALID_EXECUTION_TRANSITION', message: `Cannot move execution from ${from} to ${to}.`, category: 'validation', retryable: false }) }
