import { Prisma } from '@prisma/client'
import type { Project, ProjectStatus, ProjectType, Task, ActivityEvent, ProjectMemory } from './domain'
import { prisma } from './prisma'

type ProjectInput = { name: string; description: string; type: ProjectType }
const projectInclude = Prisma.validator<Prisma.ProjectDefaultArgs>()({ include: { tasks: true, memory: true, events: { orderBy: { createdAt: 'desc' } } } })
type ProjectRecord = Prisma.ProjectGetPayload<typeof projectInclude>
function mapMemory(row: NonNullable<ProjectRecord['memory']>): ProjectMemory { return { context: row.context, decisions: row.decisions, requirements: row.requirements, completedWork: row.completedWork, unresolvedIssues: row.unresolvedIssues } }
function mapTask(row: ProjectRecord['tasks'][number]): Task { return { id: row.id, projectId: row.projectId, title: row.title, description: row.description, status: row.status, assignedAgent: row.assignedAgent ?? undefined, dependencies: row.dependencies, input: row.input ?? undefined, output: row.output ?? undefined, error: row.error ?? undefined, retryCount: row.retryCount, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } }
function mapEvent(row: ProjectRecord['events'][number]): ActivityEvent { return { id: row.id, projectId: row.projectId, type: row.type, actor: row.actor, message: row.message, metadata: (row.metadata as Record<string, unknown> | null) ?? {}, createdAt: row.createdAt.toISOString() } }
function mapProject(row: ProjectRecord): Project { return { id: row.id, ownerId: row.ownerId, name: row.name, description: row.description, type: row.type, status: row.status, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), memory: row.memory ? mapMemory(row.memory) : { context: [], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] }, tasks: row.tasks.map(mapTask), activity: row.events.map(mapEvent), artifacts: [] } }
export async function listProjects(ownerId: string): Promise<Project[]> { return (await prisma.project.findMany({ where: { ownerId }, include: projectInclude.include, orderBy: { updatedAt: 'desc' } })).map(mapProject) }
export async function getProject(ownerId: string, id: string): Promise<Project | undefined> { const project = await prisma.project.findFirst({ where: { id, ownerId }, include: projectInclude.include }); return project ? mapProject(project) : undefined }
export async function createProject(ownerId: string, input: ProjectInput): Promise<Project> { const project = await prisma.project.create({ data: { ownerId, ...input, memory: { create: { context: [input.description], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] } }, events: { create: { type: 'project.created', actor: ownerId, message: 'Project created', metadata: {} } } }, include: projectInclude.include }); return mapProject(project) }
export async function updateProject(ownerId: string, id: string, input: Partial<ProjectInput> & { status?: ProjectStatus }): Promise<Project | undefined> { const result = await prisma.project.updateMany({ where: { id, ownerId }, data: input }); return result.count ? getProject(ownerId, id) : undefined }
export async function deleteProject(ownerId: string, id: string): Promise<boolean> { return (await prisma.project.deleteMany({ where: { id, ownerId } })).count > 0 }
export async function getMemory(ownerId: string, projectId: string): Promise<ProjectMemory | undefined> { const row = await prisma.projectMemory.findFirst({ where: { projectId, project: { ownerId } } }); return row ? mapMemory(row as NonNullable<ProjectRecord['memory']>) : undefined }
export async function updateMemory(ownerId: string, projectId: string, input: Partial<ProjectMemory>): Promise<ProjectMemory | undefined> { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; const row = await prisma.projectMemory.upsert({ where: { projectId }, create: { projectId, requirements: input.requirements ?? [], decisions: input.decisions ?? [], context: input.context ?? [], completedWork: input.completedWork ?? [], unresolvedIssues: input.unresolvedIssues ?? [] }, update: input }); return mapMemory(row as NonNullable<ProjectRecord['memory']>) }
export async function addTask(ownerId: string, projectId: string, input: { title: string; description: string; assignedAgent?: string; dependencies: string[] }): Promise<Task | undefined> { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; return prisma.$transaction(async (tx) => { const task = await tx.task.create({ data: { projectId, ...input } }); await tx.activityEvent.create({ data: { projectId, type: 'task.created', actor: ownerId, message: 'Task created', metadata: { taskId: task.id } } }); return mapTask(task) }) }
export async function updateTask(ownerId: string, projectId: string, taskId: string, input: { status?: import('@prisma/client').TaskStatus; output?: object; error?: object; retryCount?: number; assignedAgent?: string }): Promise<Task | undefined> { return prisma.$transaction(async (tx) => { const task = await tx.task.findFirst({ where: { id: taskId, projectId, project: { ownerId } } }); if (!task) return undefined; const updated = await tx.task.update({ where: { id: taskId }, data: input }); if (input.status) { const type = input.status === 'running' ? 'task.started' : input.status === 'completed' ? 'task.completed' : input.status === 'failed' ? 'task.failed' : undefined; if (type) await tx.activityEvent.create({ data: { projectId, type, actor: ownerId, message: `Task ${input.status}`, metadata: { taskId } } }) } return mapTask(updated) }) }
export async function recordEvent(ownerId: string, projectId: string, type: string, message: string, metadata: Record<string, unknown> = {}): Promise<ActivityEvent | undefined> { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; const event = await prisma.activityEvent.create({ data: { projectId, type, actor: ownerId, message, metadata } }); return mapEvent(event as ProjectRecord['events'][number]) }
