import { Prisma } from '@prisma/client'
import type { ActivityEvent, ActivityEventType, Project, ProjectMemory, ProjectStatus, ProjectType, Task, TaskStatus } from './domain'
import { AppError } from './errors'
import { prisma } from './prisma'

type ProjectInput = { name: string; description: string; type: ProjectType }
type TaskInput = { title: string; description: string; assignedAgent?: string; dependencies: string[] }
type TaskUpdate = { status?: TaskStatus; output?: object; error?: object; retryCount?: number; assignedAgent?: string }
const projectInclude = Prisma.validator<Prisma.ProjectDefaultArgs>()({ include: { tasks: true, memory: true, events: { orderBy: { createdAt: 'desc' } } } })
type ProjectRecord = Prisma.ProjectGetPayload<typeof projectInclude>
type TaskRecord = Prisma.TaskGetPayload<{}>
type MemoryRecord = Prisma.ProjectMemoryGetPayload<{}>
type EventRecord = Prisma.ActivityEventGetPayload<{}>
function mapMemory(row: MemoryRecord): ProjectMemory { return { context: row.context, decisions: row.decisions, requirements: row.requirements, completedWork: row.completedWork, unresolvedIssues: row.unresolvedIssues } }
function mapTask(row: TaskRecord): Task { return { id: row.id, projectId: row.projectId, title: row.title, description: row.description, status: row.status, assignedAgent: row.assignedAgent ?? undefined, dependencies: row.dependencies, input: row.input ?? undefined, output: row.output ?? undefined, error: row.error as Task['error'] ?? undefined, retryCount: row.retryCount, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } }
function mapEvent(row: EventRecord): ActivityEvent { return { id: row.id, projectId: row.projectId, type: row.type as ActivityEventType, actor: row.actor, message: row.message, metadata: (row.metadata as Record<string, unknown> | null) ?? {}, createdAt: row.createdAt.toISOString() } }
function mapProject(row: ProjectRecord): Project { return { id: row.id, ownerId: row.ownerId, name: row.name, description: row.description, type: row.type, status: row.status, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), memory: row.memory ? mapMemory(row.memory) : { context: [], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] }, tasks: row.tasks.map(mapTask), activity: row.events.map(mapEvent), artifacts: [] } }
const transitions: Record<TaskStatus, readonly TaskStatus[]> = { pending: ['pending', 'planning', 'running', 'failed'], planning: ['planning', 'running', 'waiting', 'failed'], running: ['running', 'waiting', 'testing', 'failed', 'completed'], waiting: ['waiting', 'running', 'failed'], testing: ['testing', 'completed', 'failed'], failed: ['failed', 'planning', 'running'], completed: ['completed'] }
function assertTransition(from: TaskStatus, to: TaskStatus): void { if (!transitions[from].includes(to)) throw new AppError({ code: 'INVALID_TASK_TRANSITION', message: `Cannot move task from ${from} to ${to}.`, category: 'validation', retryable: false }) }
export async function listProjects(ownerId: string): Promise<Project[]> { return (await prisma.project.findMany({ where: { ownerId }, include: projectInclude.include, orderBy: { updatedAt: 'desc' } })).map(mapProject) }
export async function getProject(ownerId: string, id: string): Promise<Project | undefined> { const row = await prisma.project.findFirst({ where: { id, ownerId }, include: projectInclude.include }); return row ? mapProject(row) : undefined }
export async function createProject(ownerId: string, input: ProjectInput): Promise<Project> { const row = await prisma.project.create({ data: { ownerId, ...input, memory: { create: { context: [input.description], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] } }, events: { create: { type: 'project.created', actor: ownerId, message: 'Project created', metadata: {} } } }, include: projectInclude.include }); return mapProject(row) }
export async function updateProject(ownerId: string, id: string, input: Partial<ProjectInput> & { status?: ProjectStatus }): Promise<Project | undefined> { const result = await prisma.project.updateMany({ where: { id, ownerId }, data: input }); return result.count ? getProject(ownerId, id) : undefined }
export async function deleteProject(ownerId: string, id: string): Promise<boolean> { return (await prisma.project.deleteMany({ where: { id, ownerId } })).count > 0 }
export async function getMemory(ownerId: string, projectId: string): Promise<ProjectMemory | undefined> { const row = await prisma.projectMemory.findFirst({ where: { projectId, project: { ownerId } } }); return row ? mapMemory(row) : undefined }
export async function updateMemory(ownerId: string, projectId: string, input: Partial<ProjectMemory>): Promise<ProjectMemory | undefined> { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; const row = await prisma.projectMemory.upsert({ where: { projectId }, create: { projectId, requirements: input.requirements ?? [], decisions: input.decisions ?? [], context: input.context ?? [], completedWork: input.completedWork ?? [], unresolvedIssues: input.unresolvedIssues ?? [] }, update: input }); return mapMemory(row) }
export async function addTask(ownerId: string, projectId: string, input: TaskInput): Promise<Task | undefined> { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; const uniqueDependencies = [...new Set(input.dependencies)]; if (uniqueDependencies.includes(projectId)) throw new AppError({ code: 'INVALID_DEPENDENCY', message: 'A task cannot depend on its project ID.', category: 'validation', retryable: false }); return prisma.$transaction(async (tx) => { if (uniqueDependencies.length && await tx.task.count({ where: { id: { in: uniqueDependencies }, projectId } }) !== uniqueDependencies.length) throw new AppError({ code: 'INVALID_DEPENDENCY', message: 'Every dependency must be an existing task in the same project.', category: 'validation', retryable: false }); const task = await tx.task.create({ data: { projectId, ...input, dependencies: uniqueDependencies } }); await tx.activityEvent.create({ data: { projectId, type: 'task.created', actor: ownerId, message: 'Task created', metadata: { taskId: task.id } }); return mapTask(task) }) }
export async function updateTask(ownerId: string, projectId: string, taskId: string, input: TaskUpdate): Promise<Task | undefined> { return prisma.$transaction(async (tx) => { const task = await tx.task.findFirst({ where: { id: taskId, projectId, project: { ownerId } } }); if (!task) return undefined; if (input.status) assertTransition(task.status, input.status); const updated = await tx.task.update({ where: { id: taskId }, data: { ...input, output: input.output as Prisma.InputJsonValue | undefined, error: input.error as Prisma.InputJsonValue | undefined } }); if (input.status && input.status !== task.status) { const type = input.status === 'running' ? 'task.started' : input.status === 'completed' ? 'task.completed' : input.status === 'failed' ? 'task.failed' : undefined; if (type) await tx.activityEvent.create({ data: { projectId, type, actor: ownerId, message: `Task ${input.status}`, metadata: { taskId } } }) } return mapTask(updated) }) }
export async function recordEvent(ownerId: string, projectId: string, type: ActivityEventType, message: string, metadata: Record<string, unknown> = {}): Promise<ActivityEvent | undefined> { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; const event = await prisma.activityEvent.create({ data: { projectId, type, actor: ownerId, message, metadata } }); return mapEvent(event) }
