import type { Project, ProjectStatus, ProjectType, Task, ActivityEvent } from './domain'
import { prisma } from './prisma'

type ProjectInput = { name: string; description: string; type: ProjectType }
const includeProject = { tasks: true, memory: true, events: { orderBy: { createdAt: 'desc' as const } } }
function mapProject(row: any): Project { return { ...row, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), memory: row.memory ?? { context: [], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] }, tasks: row.tasks.map((task: any) => ({ ...task, createdAt: task.createdAt.toISOString(), updatedAt: task.updatedAt.toISOString() })), activity: row.events.map((event: any) => ({ ...event, metadata: event.metadata ?? {}, createdAt: event.createdAt.toISOString() })), artifacts: [] } }
export async function listProjects(ownerId: string) { return (await prisma.project.findMany({ where: { ownerId }, include: includeProject, orderBy: { updatedAt: 'desc' } })).map(mapProject) }
export async function getProject(ownerId: string, id: string) { const project = await prisma.project.findFirst({ where: { id, ownerId }, include: includeProject }); return project ? mapProject(project) : undefined }
export async function createProject(ownerId: string, input: ProjectInput) { const project = await prisma.project.create({ data: { ownerId, ...input, memory: { create: { context: [input.description], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] } }, events: { create: { type: 'project.created', actor: ownerId, message: 'Project created', metadata: {} } } }, include: includeProject }); return mapProject(project) }
export async function updateProject(ownerId: string, id: string, input: Partial<ProjectInput> & { status?: ProjectStatus }) { const project = await prisma.project.updateMany({ where: { id, ownerId }, data: input }); if (!project.count) return undefined; return getProject(ownerId, id) }
export async function deleteProject(ownerId: string, id: string) { const result = await prisma.project.deleteMany({ where: { id, ownerId } }); return result.count > 0 }
export async function addTask(ownerId: string, projectId: string, input: { title: string; description: string; assignedAgent?: string; dependencies: string[] }) { const project = await prisma.project.findFirst({ where: { id: projectId, ownerId }, select: { id: true } }); if (!project) return undefined; const task = await prisma.task.create({ data: { projectId, ...input }, }); await prisma.activityEvent.create({ data: { projectId, type: 'task.created', actor: ownerId, message: 'Task created', metadata: { taskId: task.id } } }); return task }
