import { Prisma } from '@prisma/client'
import type { AgentRunStatus, ExecutionStatus } from '@prisma/client'
import type { ActivityEventType } from './domain'
import { AppError } from './errors'
import { authorizeAgentRun, authorizeProject, authorizeTask, asJson } from './authorization'
import { assertAgentTransition } from './agent-runtime'
import { assertExecutionTransition } from './execution'
import { prisma } from './prisma'
export type AgentRunInput = { projectId: string; taskId?: string; agentId: string; role: string; input?: Record<string, unknown>; metadata?: Record<string, unknown> }
export async function createAgentRun(ownerId: string, input: AgentRunInput) { await authorizeProject(ownerId, input.projectId); if (input.taskId) await authorizeTask(ownerId, input.projectId, input.taskId); return prisma.$transaction(async (tx) => tx.agentRun.create({ data: { projectId: input.projectId, taskId: input.taskId, agentId: input.agentId, role: input.role, input: asJson(input.input), metadata: asJson(input.metadata), status: 'queued' } })) }
export async function updateAgentRun(ownerId: string, projectId: string, id: string, status: AgentRunStatus, output?: Record<string, unknown>, error?: Record<string, unknown>) { const run = await authorizeAgentRun(ownerId, projectId, id); assertAgentTransition(run.status, status); const updated = await prisma.agentRun.update({ where: { id }, data: { status, output: asJson(output), error: asJson(error), startedAt: status === 'running' && !run.status.includes('running') ? new Date() : undefined, completedAt: ['completed', 'failed', 'blocked'].includes(status) ? new Date() : undefined } }); if (status !== run.status) { const event: ActivityEventType | undefined = status === 'running' ? 'agent.started' : status === 'completed' ? 'agent.completed' : status === 'failed' ? 'agent.failed' : status === 'blocked' ? 'agent.blocked' : undefined; if (event) await prisma.activityEvent.create({ data: { projectId, type: event, actor: ownerId, message: `Agent ${status}`, metadata: { agentRunId: id } } }) } return updated }
export type ExecutionRecordInput = { projectId: string; taskId?: string; agentRunId?: string; kind: string; result: { status: ExecutionStatus; stdout: string; stderr: string; exitCode?: number; durationMs: number; error?: unknown; metadata: Record<string, unknown> } }
async function authorizeExecution(ownerId: string, input: ExecutionRecordInput) { if (input.taskId) await authorizeTask(ownerId, input.projectId, input.taskId); else await authorizeProject(ownerId, input.projectId); if (input.agentRunId) { const run = await authorizeAgentRun(ownerId, input.projectId, input.agentRunId); if (input.taskId && run.taskId !== input.taskId) throw new AppError({ code: 'RESOURCE_MISMATCH', message: 'Execution resources do not match.', category: 'validation', retryable: false }) } }
export async function createExecutionRecord(ownerId: string, input: ExecutionRecordInput) { await authorizeExecution(ownerId, input); return prisma.executionRecord.create({ data: { projectId: input.projectId, taskId: input.taskId, agentRunId: input.agentRunId, kind: input.kind, status: input.result.status, stdout: input.result.stdout, stderr: input.result.stderr, exitCode: input.result.exitCode, durationMs: input.result.durationMs, error: asJson(input.result.error), metadata: asJson(input.result.metadata) } }) }
export async function updateExecutionRecord(ownerId: string, projectId: string, id: string, status: ExecutionStatus, patch: { stdout?: string; stderr?: string; exitCode?: number; durationMs?: number; error?: unknown; metadata?: Record<string, unknown> } = {}) { const record = await prisma.executionRecord.findFirst({ where: { id, projectId, project: { ownerId } } }); if (!record) return undefined; assertExecutionTransition(record.status, status); return prisma.executionRecord.update({ where: { id }, data: { status, ...patch, error: asJson(patch.error), metadata: asJson(patch.metadata), startedAt: status === 'running' && !record.startedAt ? new Date() : undefined, completedAt: ['succeeded', 'failed', 'timed_out', 'rejected'].includes(status) ? new Date() : undefined } }) }
