import { describe, expect, it } from 'vitest'
import { createDefaultAgentRegistry, AgentRegistry, FoundationAgent, assertAgentTransition } from '../lib/agent-runtime'
import { assertExecutionTransition, defaultExecutionLimits, RejectingExecutor, validateExecutionLimits } from '../lib/execution'
import { createDefaultToolRegistry } from '../lib/tools-runtime'
import { FoundationVerifier } from '../lib/verification-runtime'
import { OrchestratorFoundation } from '../lib/orchestrator-foundation'
const project = { id: 'ckproject123456789012345678', ownerId: 'user', name: 'Project', description: 'A valid project fixture', type: 'web_app', status: 'draft', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), memory: { context: [], decisions: [], requirements: [], completedWork: [], unresolvedIssues: [] }, tasks: [], activity: [], artifacts: [] } as const
it('registers defaults, rejects duplicates, and returns unknown agents safely', () => { const registry = new AgentRegistry(); registry.register(new FoundationAgent('one', 'test', 'test')); expect(() => registry.register(new FoundationAgent('one', 'test', 'test'))).toThrow('already registered'); expect(registry.get('missing')).toBeUndefined(); expect(createDefaultAgentRegistry().list()).toHaveLength(6) })
it('validates agent transitions', () => { expect(() => assertAgentTransition('queued', 'running')).not.toThrow(); expect(() => assertAgentTransition('queued', 'completed')).toThrow('Invalid agent transition') })
it('validates execution transitions and limits', () => { expect(() => assertExecutionTransition('queued', 'rejected')).not.toThrow(); expect(() => assertExecutionTransition('queued', 'succeeded')).toThrow('INVALID_EXECUTION_TRANSITION'); expect(validateExecutionLimits(defaultExecutionLimits)).toEqual(defaultExecutionLimits); expect(() => validateExecutionLimits({ ...defaultExecutionLimits, timeoutMs: 1 })).toThrow('INVALID_EXECUTION_LIMITS') })
it('rejecting executor fails closed including network policy', async () => { const executor = new RejectingExecutor(); const result = await executor.execute({ projectId: project.id, kind: 'build', input: {}, limits: defaultExecutionLimits }); expect(result.status).toBe('rejected'); const network = await executor.execute({ projectId: project.id, kind: 'build', input: {}, limits: { ...defaultExecutionLimits, allowNetwork: true } }); expect(network.error?.code).toBe('NETWORK_NOT_ALLOWED') })
it('keeps verification evidence-gated', async () => { const verifier = new FoundationVerifier(); expect((await verifier.verifyTests({ project })).status).toBe('incomplete'); expect((await verifier.verifyTests({ project, test: { status: 'succeeded', stdout: '', stderr: '', exitCode: 0, durationMs: 1, metadata: {} } })).status).toBe('passed') })
it('keeps the orchestrator as a plan-only representation', () => { expect(new OrchestratorFoundation().plan('objective').map((step) => step.kind)).toEqual(['plan', 'execute', 'build', 'test', 'verify']) })
it('exposes disabled metadata-only tools', () => { const tools = createDefaultToolRegistry().list(); expect(tools).toHaveLength(7); expect(tools.every((tool) => tool.enabled === false)).toBe(true) })
